In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [17]:

path = "./iris.data"
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(path, names = headernames)
dataset.head()


sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)


In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [37]:
#train the model with the help of KNeighborsClassifier class of sklearn 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
for i in range(1,20):
    classifier = KNeighborsClassifier(n_neighbors = i)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    result = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(result)
    result1 = classification_report(y_test, y_pred)
    print("Classification Report:",result1)
    result2 = accuracy_score(y_test,y_pred)
    print("i", i,"Accuracy:",result2)

Confusion Matrix:
[[21  1  0]
 [ 0 19  3]
 [ 0  2 14]]
Classification Report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      0.95      0.98        22
Iris-versicolor       0.86      0.86      0.86        22
 Iris-virginica       0.82      0.88      0.85        16

      micro avg       0.90      0.90      0.90        60
      macro avg       0.90      0.90      0.90        60
   weighted avg       0.90      0.90      0.90        60

i 1 Accuracy: 0.9
Confusion Matrix:
[[22  0  0]
 [ 0 19  3]
 [ 0  4 12]]
Classification Report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.83      0.86      0.84        22
 Iris-virginica       0.80      0.75      0.77        16

      micro avg       0.88      0.88      0.88        60
      macro avg       0.88      0.87      0.87        60
   weighted avg       0.88      0.88      0.88        60

i 2 Accuracy: 0.883333

Confusion Matrix: [[22  0  0]
 [ 0 19  3]
 [ 0  4 12]]
Classification Report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.83      0.86      0.84        22
 Iris-virginica       0.80      0.75      0.77        16

      micro avg       0.88      0.88      0.88        60
      macro avg       0.88      0.87      0.87        60
   weighted avg       0.88      0.88      0.88        60

Accuracy: 0.8833333333333333
